/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class experta_jell_utilz_Functionz */

#ifndef _Included_experta_jell_utilz_Functionz
#define _Included_experta_jell_utilz_Functionz
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     experta_jell_utilz_Functionz
 * Method:    fibNr
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_experta_jell_utilz_Functionz_fibNr
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
